version: '3.9'

services:
  backend:
    container_name: yolo-backend
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - yolo-client
    depends_on:
      - db  
  
  client:
    container_name: yolo-frontend
    build: ./client 
    ports:
      - "3000:3000"
    networks:
      - yolo-client
    depends_on:
      - backend

  db:
      image: mongo
      ports:
        - 27017:27017
      container_name: mongo-db
      networks:
        - yolo-client
      volumes:
        - mongo-data:/data/db      

networks:
  yolo-client:
    driver: bridge

volumes:
  mongo-data:
    driver: local    