apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9hbmlzaGFkYW5pZWxzOnlWUzFVY1p5U2tmhtbS5tb25nb2RiLm5ldC95b2xvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==